name: Run forward compatibility tests for posjsonhelper

on:
  push:

jobs:

  integraion_tests:
#    needs: [compilation_and_unit_tests]
    runs-on: ubuntu-latest
    name: "Integration and functional tests in core module"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        # Install JDKs and maven toolchain
      - uses: actions/setup-java@v3
        name: Set up JDK 11
        id: setupJava11
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: actions/setup-java@v3
        name: Set up JDK 17
        id: setupJava17
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Set up JDK 1.8
        id: setupJava8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: cactuslab/maven-toolchains-xml-action@v1
        with:
          toolchains: |
            [
            {"jdkVersion": "8", "jdkHome": "${{steps.setupJava8.outputs.path}}"},
            {"jdkVersion": "11", "jdkHome": "${{steps.setupJava11.outputs.path}}"},
            {"jdkVersion": "17", "jdkHome": "${{steps.setupJava17.outputs.path}}"}
            ]

      - name: Install library for postgres
        run: sudo apt-get update -y && sudo apt-get -y install libpq-dev postgresql-client
      # Executing gmavenplus plugin
      # https://github.com/groovy/GMavenPlus/issues/43
      - uses: actions/setup-java@v3
        name: Set up JDK 11 for hibernate6 tests
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run tests for hibernate6
        run: ./mvnw -DskipTests  --quiet -P forward_compatibility_tests clean install && ./mvnw -pl :hibernate6-tests-core,:hibernate6-forward-compatibility-tests -P forward_compatibility_tests test